[inputs.demo1]
context_key = "demo1"

[inputs.demo2]
context_key = "demo2"

[inputs.demo3]
context_key = "demo3"

[inputs.demo4]
context_key = "demo4"

[inputs.text_value]
context_key = "text_value"

[inputs.text_upper]
context_key = "text_value"
transform = "upper"

[inputs.number_value]
context_key = "number_value"

[inputs.price_value]
context_key = "price_value"

[inputs.timestamp]
context_key = "timestamp"

[inputs.missing_field]
context_key = "nonexistent_key"
default = "N/A"

[inputs.city]
context_key = "city"
default = "Unknown City"
