[layouts.demo]
name = "Demo Display"

[[layouts.demo.lines]]
input = "demo1"
index = 0
formatter = "text"

[[layouts.demo.lines]]
input = "demo2"
index = 1
formatter = "text"

[[layouts.demo.lines]]
input = "demo3"
index = 2
formatter = "text"

[[layouts.demo.lines]]
input = "demo4"
index = 3
formatter = "text"

[layouts.advanced]
name = "Advanced Features Demo"

[[layouts.advanced.lines]]
input = "text_value"
index = 0
formatter = "text"

[[layouts.advanced.lines]]
input = "text_upper"
index = 1
formatter = "uppercase_text"

[[layouts.advanced.lines]]
input = "number_value"
index = 2
formatter = "number_with_commas"

[[layouts.advanced.lines]]
input = "price_value"
index = 3
formatter = "price_usd"

[[layouts.advanced.lines]]
input = "timestamp"
index = 4
formatter = "datetime_short"

[[layouts.advanced.lines]]
input = "missing_field"
index = 5
formatter = "text"

[[layouts.advanced.lines]]
input = "city"
index = 6
formatter = "text"
