#:schema ../schemas/viewtext.json

[inputs.temperature]
context_key = "temperature"
type = "float"

[inputs.price_value]
context_key = "price_value"
type = "float"

[inputs.text_value]
context_key = "text_value"
type = "str"

[inputs.number_value]
context_key = "number_value"
type = "float"

[inputs.timestamp]
context_key = "timestamp"
type = "int"

[inputs.demo1]
context_key = "demo1"
type = "str"

[inputs.demo2]
context_key = "demo2"
type = "str"

[inputs.demo3]
context_key = "demo3"
type = "str"

[layouts.weather_dict]
name = "Weather Dictionary Display"

[[layouts.weather_dict.items]]
input = "temperature"
key = "temp"
formatter = "number"

[layouts.weather_dict.items.formatter_params]
suffix = "Â°"
decimals = 1

[[layouts.weather_dict.items]]
input = "price_value"
key = "price"
formatter = "price"

[layouts.weather_dict.items.formatter_params]
symbol = "$"
decimals = 2

[[layouts.weather_dict.items]]
input = "text_value"
key = "message"
formatter = "text"

[[layouts.weather_dict.items]]
input = "timestamp"
key = "time"
formatter = "datetime"

[layouts.weather_dict.items.formatter_params]
format = "%Y-%m-%d %H:%M:%S"

[layouts.simple_dict]
name = "Simple Dictionary"

[[layouts.simple_dict.items]]
input = "demo1"
key = "greeting"

[[layouts.simple_dict.items]]
input = "demo2"
key = "world"

[[layouts.simple_dict.items]]
input = "demo3"
key = "app"

[layouts.mixed_line]
name = "Traditional Line Layout"

[[layouts.mixed_line.lines]]
input = "demo1"
index = 0

[[layouts.mixed_line.lines]]
input = "demo2"
index = 1

[[layouts.mixed_line.lines]]
input = "demo3"
index = 2
