[inputs.demo1]
context_key = "demo1"

[inputs.demo2]
context_key = "demo2"

[inputs.demo3]
context_key = "demo3"

[inputs.demo4]
context_key = "demo4"

[inputs.text_value]
context_key = "text_value"

[inputs.text_upper]
context_key = "text_value"
transform = "upper"

[inputs.number_value]
context_key = "number_value"

[inputs.price_value]
context_key = "price_value"

[inputs.timestamp]
context_key = "timestamp"

[inputs.missing_field]
context_key = "nonexistent_key"
default = "N/A"

[inputs.city]
context_key = "city"
default = "Unknown City"

[layouts.demo]
name = "Demo Display"

[[layouts.demo.lines]]
input = "demo1"
index = 0
formatter = "text"

[[layouts.demo.lines]]
input = "demo2"
index = 1
formatter = "text"

[[layouts.demo.lines]]
input = "demo3"
index = 2
formatter = "text"

[[layouts.demo.lines]]
input = "demo4"
index = 3
formatter = "text"

[layouts.advanced]
name = "Advanced Features Demo"

[[layouts.advanced.lines]]
input = "text_value"
index = 0
formatter = "text"

[[layouts.advanced.lines]]
input = "text_upper"
index = 1
formatter = "text"

[[layouts.advanced.lines]]
input = "number_value"
index = 2
formatter = "number"

[[layouts.advanced.lines]]
input = "price_value"
index = 3
formatter = "price"

[[layouts.advanced.lines]]
input = "timestamp"
index = 4
formatter = "datetime"

[[layouts.advanced.lines]]
input = "missing_field"
index = 5
formatter = "text"

[[layouts.advanced.lines]]
input = "city"
index = 6
formatter = "text"
